import React from 'react';


const Movies = () => {
    const movies = [
      {movie: 'Adjustment Bureau', slug: 'adjust', url:'https://www.youtube.com/watch?v=wZJ0TP4nTaE' },
      {movie: 'Aeon Flux', slug: 'aeon', url:'https://www.youtube.com/watch?v=d11loPMnC2w' },
      {movie: 'Akira', slug: 'akira', url:'https://www.youtube.com/watch?v=i_MONOV1_sc' },
      {movie: 'Aladdin', slug: 'aladin', url:'https://www.youtube.com/watch?v=HlULSKurtzg' },
      {movie: 'Alien', slug: 'alien', url:'https://www.youtube.com/watch?v=LjLamj-b0I8' },
      {movie: 'Alien 2', slug: '', url:'https://www.youtube.com/watch?v=XKSQmYUaIyE' },
      {movie: '***American Beauty', slug: '', url:'https://www.youtube.com/watch?v=3ycmmJ6rxA8' },
      {movie: '***Amile', slug: '', url:'https://www.youtube.com/watch?v=HUECWi5pX7o' },
      {movie: 'Anchorman', slug: 'anchorman', url:'https://www.youtube.com/watch?v=-T3wnP91OnI' },
      {movie: 'Apocalypto', slug: 'apoalypto', url:'https://www.youtube.com/watch?v=pXuwjdQx924' },
      {movie: '***Atlantis', slug: 'atlantis', url:'https://www.youtube.com/watch?v=sZIimDPZQwg' },
      {movie: '***Babadook', slug: 'babadook', url:'https://www.youtube.com/watch?v=k5WQZzDRVtw' },
      {movie: 'Batteries not Included', slug: 'batteries', url:'https://www.youtube.com/watch?v=h25ZL7fxZ8o' },
      {movie: '***Beach', slug: 'beach', url:'https://www.youtube.com/watch?v=RweHayPG3wA' },
      {movie: 'Behind Enemy Lines', slug: '', url:'https://www.youtube.com/watch?v=PUeWBp_kmuo' },
      {movie: 'Beowolf', slug: 'beowolf', url:'https://www.youtube.com/watch?v=DaShOr5AeKA' },
      {movie: 'Beatlejuice', slug: 'beetlejuice', url:'https://www.youtube.com/watch?v=ickbVzajrk0' },
      {movie: '***Big Fish', slug: 'bigFish', url:'https://www.youtube.com/watch?v=dF-Iy7vIOJA' },
      {movie: 'Big Lebowski', slug: 'bigLebowski', url:'https://www.youtube.com/watch?v=cd-go0oBF4Y' },
      {movie: 'Black Hawk Down', slug: 'blackHawk', url:'https://www.youtube.com/watch?v=2GfBkC3qs78' },
      {movie: 'Blade', slug: 'Blade', url:'https://www.youtube.com/watch?v=kaU2A7KyOu4' },
      {movie: 'Blair Witch Project', slug: 'blairWhitch', url:'https://www.youtube.com/watch?v=a_Hw4bAUj8A' },
      {movie: 'Boondock Saints', slug: 'boondock', url:'https://www.youtube.com/watch?v=ydXojYfCF3I' },
      {movie: '***Bram Stokers Dracula', slug: 'bram', url:'https://www.youtube.com/watch?v=PlDbxogHPao' },
      {movie: 'Bubba Hotep', slug: 'bubba', url:'https://www.youtube.com/watch?v=pa9331xmvhg' },
      {movie: 'Burbs', slug: 'burbs', url:'https://www.youtube.com/watch?v=pyRUijyrXr4' },
      {movie: 'Cabin in the Woods', slug: 'cabin', url:'https://www.youtube.com/watch?v=NsIilFNNmkY' },
      {movie: '***Castaway', slug: 'castaway', url:'https://www.youtube.com/watch?v=2TWYDogv4WQ' },
      {movie: 'Cell', slug: 'cell', url:'https://www.youtube.com/watch?v=RQUdbvUVfgE' },
      {movie: 'Cocoon', slug: 'cocoon', url:'https://www.youtube.com/watch?v=HHamE8gmA8Q' },
      {movie: 'Charlie and the Chocolate Factory', slug: 'charlie', url:'https://www.youtube.com/watch?v=OFVGCUIXJls' },
      {movie: 'Chicken Run', slug: 'chicken', url:'https://www.youtube.com/watch?v=AEOfT7hUcDs' },
      {movie: 'Christmas Story', slug: 'christmas', url:'https://www.youtube.com/watch?v=cfjEZ88NHBw' },
      {movie: '***City of Lost Children', slug: 'city', url:'https://www.youtube.com/watch?v=Pa7oVPru4J8' },
      {movie: 'Clerks', slug: 'clerks', url:'https://www.youtube.com/watch?v=Mlfn5n-E2WE' },
      {movie: 'Cloverfield', slug: 'clover', url:'https://www.youtube.com/watch?v=wxqSIsxMlYQ' },
      {movie: 'Clue', slug: 'clue', url:'https://www.youtube.com/watch?v=cDDdeHtrxfA' },
      {movie: '***Color of Magic', slug: 'color', url:'https://www.youtube.com/watch?v=f-3YshvxA1M' },
      {movie: '***Coraline', slug: 'cora', url:'https://www.youtube.com/watch?v=XyUwEO7xelY' },
      {movie: 'Cowboys and Aliens', slug: 'cowboys', url:'https://www.youtube.com/watch?v=zH7KZD5vGBY' },
      {movie: 'Crocodile Dundee', slug: 'cd1', url:'https://www.youtube.com/watch?v=rijQ5oBFlO0' },
      {movie: 'Crocodile Dundee 2', slug: 'cd2', url:'https://www.youtube.com/watch?v=oYaOhlHnuZw' },
      {movie: '***Crouching Tiger Hidden Dragon', slug: 'crouching', url:'https://www.youtube.com/watch?v=gLpZ_5bHmo8' },
      {movie: 'Dale and Tucker Vs Evil', slug: 'dale', url:'https://www.youtube.com/watch?v=l1t8OZn_uhE' },
      {movie: '***Dogma', slug: 'dogma', url:'https://www.youtube.com/watch?v=20CRw3XdETA' },
      {movie: '***Donnie Darko', slug: 'donnie', url:'' },
      {movie: 'Drag me to Hell', slug: 'drag', url:'https://www.youtube.com/watch?v=PPOaxHqoYxo' },
      {movie: 'Edward Scissorhands', slug: 'edward', url:'https://www.youtube.com/watch?v=M94yyfWy-KI' },
      {movie: 'Enemy at the Gates', slug: 'enemy', url:'https://www.youtube.com/watch?v=4O-sMh_DO6I' },
      {movie: 'ET', slug: 'et', url:'https://www.youtube.com/watch?v=qYAETtIIClk' },
      {movie: 'Eternal Sunshine of the Spotless Mind', slug: 'eternal', url:'https://www.youtube.com/results?search_query=eternal+sunshine+of+the+spotless+mind+official+trailer'},
      {movie: 'Evil Dead', slug: 'evil', url:'https://www.youtube.com/watch?v=coGH4OaR9hc' },
      {movie: 'Evil Dead 2', slug: 'evil2', url:'https://www.youtube.com/watch?v=6lM3NPeEG24' },
      {movie: 'Evil Dead 3', slug: 'evil3', url:'https://www.youtube.com/watch?v=UHZQEtG8xYo' },
      {movie: 'eXistenz', slug: 'exist', url:'https://www.youtube.com/watch?v=HAdbdUt_h9M' },
      {movie: 'Explorers', slug: 'explorers', url:'https://www.youtube.com/watch?v=HAdbdUt_h9M' },
      {movie: 'Fall', slug: 'fall', url:'https://www.youtube.com/watch?v=IwsYyRc9j4g' },
      {movie: 'Fantastic fear of Everything', slug: 'fear', url:'https://www.youtube.com/watch?v=HIjhgXteLlY' },
      {movie: '***Fantastic Mr. Fox', slug: 'fox', url:'https://www.youtube.com/watch?v=n2igjYFojUo' },
      {movie: '***Fifth Element', slug: 'fifth', url:'https://www.youtube.com/watch?v=fQ9RqgcR24g' },
      {movie: '***Fight Club', slug: 'fightClub', url:'https://www.youtube.com/watch?v=Y6cwmHL2tFI' },
      {movie: '***Finding a friend for the End of the World', slug: 'friend', url:'https://www.youtube.com/watch?v=EmXWcXKXWBk' },
      {movie: 'Flight of the Navigator', slug: 'navigator', url:'https://www.youtube.com/watch?v=gVebPEYiq2o' },
      {movie: 'Forrest Gump', slug: 'forrest', url:'https://www.youtube.com/watch?v=XHhAG-YLdk8' },
      {movie: 'Fury Road', slug: 'fury', url:'https://www.youtube.com/watch?v=hEJnMQG9ev8' },
      {movie: 'Ghostbusters', slug: 'ghostbuster', url:'https://www.youtube.com/watch?v=6hDkhw5Wkas' },
      {movie: 'Ghostbusters 2', slug: 'ghostbuster2', url:'https://www.youtube.com/watch?v=UnzH75FlwvU' },
      {movie: '***Ghost Dog', slug: 'ghostdog', url:'https://www.youtube.com/watch?v=Rml5ehAl7SM' },
      {movie: '***Goonies', slug: 'goonies', url:'https://www.youtube.com/watch?v=hJ2j4oWdQtU' },
      {movie: '***Gladiator', slug: 'gladiator', url:'https://www.youtube.com/watch?v=owK1qxDselE' },
      {movie: 'Grand Budapest Hotel', slug: 'budapest', url:'https://www.youtube.com/watch?v=zru-1DbbcsA' },
      {movie: 'Green Street Hooligans', slug: 'hooligans', url:'https://www.youtube.com/watch?v=EAe-1Lv1KYU' },
      {movie: 'Grudge', slug: 'grudge', url:'https://www.youtube.com/watch?v=YC3bzK_i9_s' },
      {movie: 'Guardians of the Galaxy', slug: 'gaurdians', url:'https://www.youtube.com/watch?v=yM7VVKxjeag' },
      {movie: 'Guardians of the Galaxy 2', slug: 'gaurdians2', url:'https://www.youtube.com/watch?v=2LIQ2-PZBC8' },
      {movie: '***Hectors Search for Happiness', slug: 'hectors', url:'https://www.youtube.com/watch?v=iWFVAIbIkS4' },
      {movie: '***Hidden', slug: 'hidden', url:'https://www.youtube.com/watch?v=iWFVAIbIkS4' },
      {movie: 'Hogfather', slug: 'hogfather', url:'https://www.youtube.com/watch?v=cSOUIuGcY74' },
      {movie: '***House of Flying Daggers', slug: 'daggers', url:'https://www.youtube.com/watch?v=-GLVaSYzAvg' },
      {movie: 'Hugo', slug: 'hugo', url:'https://www.youtube.com/watch?v=Hv3obL9HqyY' },
      {movie: 'Idle Hands', slug: 'idle', url:'https://www.youtube.com/watch?v=HcVrp--9UUc' },
      {movie: 'In the Mouth of Madness', slug: 'mouth', url:'https://www.youtube.com/watch?v=AlugldzO9zY' },
      {movie: '***Indiana Jones', slug: 'ij1', url:'https://www.youtube.com/watch?v=HqOSLZl9GUo' },
      {movie: '***Indiana Jones 2', slug: 'ij2', url:'https://www.youtube.com/watch?v=HOwWfns4qqw' },
      {movie: '***Indiana Jones 3', slug: 'ij3', url:'https://www.youtube.com/watch?v=sagmdpkWUqc' },
      {movie: 'Inglorious Bastards', slug: 'inglorious', url:'https://www.youtube.com/watch?v=qRYDNWXuip8' },
      {movie: 'Inception', slug: 'inception', url:'' },
      {movie: 'Interstellar', slug: 'interstellar', url:'' },
      {movie: 'Interview with a Vampire', slug: 'interview', url:'' },
      {movie: 'Island', slug: 'island', url:'' },
      {movie: 'Isle of Dogs', slug: 'isle', url:'' },
      {movie: '***Its a Wonderful Life', slug: 'wonderful', url:'' },
      {movie: 'Joe Dirt', slug: 'joe', url:'' },
      {movie: '***Jurassic Park', slug: 'jurasic', url:'' },
      {movie: 'Jurasic World Fallen Kingdom', slug: 'fallen', url:'' },
      {movie: 'Kick Ass', slug: 'kick', url:'' },
      {movie: '***Kill Bill', slug: 'kill1', url:'' },
      {movie: '***Kill Bill 2', slug: 'kill2', url:'' },
      {movie: '***King Arthur', slug: 'kill3', url:'' },
      {movie: 'kingsman', slug: 'kingman', url:'' },
      {movie: '***Kung Fu Hustle', slug: '', url:'' },
      {movie: '***Laberinth', slug: '', url:'' },
      {movie: 'Legend of the Drunken Master', slug: '', url:'' },
      {movie: 'Legend of Sleepy Hollow', slug: '', url:'' },
      {movie: '***Let the Right One In', slug: '', url:'' },
      {movie: '***Life of Pi', slug: '', url:'' },
      {movie: 'Little Evil', slug: '', url:'' },
      {movie: 'Little Prince', slug: '', url:'' },
      {movie: '***Lord of the Rings', slug: '', url:'' },
      {movie: '***Lord of the Rings 2', slug: '', url:'' },
      {movie: '***Lord of the Rings 3', slug: '', url:'' },
      {movie: 'Lucy', slug: '', url:'' },
      {movie: 'Maze Runner', slug: '', url:'' },
      {movie: 'Mexican', slug: '', url:'' },
      {movie: 'Momento', slug: '', url:'' },
      {movie: 'Moon', slug: '', url:'' },
      {movie: '***Moonrise Kingdom', slug: '', url:'' },
      {movie: 'Mystery Men', slug: '', url:'' },
      {movie: '***Nacho Libre', slug: '', url:'' },
      {movie: 'Napoleon Dynomite', slug: '', url:'' },
      {movie: 'National Treasure', slug: '', url:'' },
      {movie: '***Neverending Story', slug: '', url:'' },
      {movie: '***O Brother Where Art Thou', slug: '', url:'' },
      {movie: 'Odd Thomas', slug: '', url:'' },
      {movie: 'Office Space', slug: '', url:'' },
      {movie: '***Once Upon a Time in Mexico', slug: '', url:'' },
      {movie: 'Orphanage', slug: '', url:'' },
      {movie: 'Others', slug: '', url:'' },
      {movie: 'Pans Labrynth', slug: '', url:'' },
      {movie: 'Pee Wee Hermans big Adventure', slug: '', url:'' },
      {movie: 'Postman', slug: '', url:'' },
      {movie: '***Princess Bride', slug: '', url:'' },
      {movie: 'Princess Mononoke', slug: '', url:'' },
      {movie: '***Pulp Fiction', slug: '', url:'' },
      {movie: 'Quiet Place', slug: '', url:'' },
      {movie: 'Red', slug: '', url:'' },
      {movie: 'Ring', slug: '', url:'' },
      {movie: 'Romancing the Stone', slug: '', url:'' },
      {movie: 'Romeo and Juliet', slug: '', url:'' },
      {movie: 'Saving Private Ryan', slug: '', url:'' },
      {movie: 'Scott Pilgrim Vs. the World', slug: '', url:'' },
      {movie: 'Scrooged', slug: '', url:'' },
      {movie: '***Second Hand Lions', slug: '', url:'' },
      {movie: '***Secret Life of Walter Mitty', slug: '', url:'' },
      {movie: 'Secret Window', slug: '', url:'' },
      {movie: '***Series of unfortunate Events', slug: '', url:'' },
      {movie: 'Sherlock Holmes', slug: '', url:'' },
      {movie: 'Shoot em Up', slug: '', url:'' },
      {movie: 'Shutter Island', slug: '', url:'' },
      {movie: 'Sicarrio', slug: '', url:'' },
      {movie: 'Simple Plan', slug: '', url:'' },
      {movie: '***Sin City', slug: '', url:'' },
      {movie: '***Snatch', slug: '', url:'' },
      {movie: 'Space Balls', slug: '', url:'' },
      {movie: 'Star Wars 4', slug: '', url:'' },
      {movie: 'Star Wars 5', slug: '', url:'' },
      {movie: 'Star Wars 6', slug: '', url:'' },
      {movie: 'Star Wars 7', slug: '', url:'' },
      {movie: 'Sucker Punch', slug: '', url:'' },
      {movie: 'Super 8', slug: '', url:'' },
      {movie: 'Swiss Family Robinson', slug: '', url:'' },
      {movie: 'Terminator', slug: '', url:'' },
      {movie: 'Terminator 2', slug: '', url:'' },
      {movie: '***They Look Like People', slug: '', url:'' },
      {movie: 'Thin Red Line', slug: '', url:'' },
      {movie: '***Troy', slug: '', url:'' },
      {movie: 'Truman Show', slug: '', url:'' },
      {movie: '***Unbreakable', slug: '', url:'' },
      {movie: '***Underworld', slug: '', url:'' },
      {movie: 'Very Bad Things', slug: '', url:'' },
      {movie: 'Village', slug: '', url:'' },
      {movie: 'Waterboy', slug: '', url:'' },
      {movie: '***Way of the Gun', slug: '', url:'' },
      {movie: 'What Dreams May Come', slug: '', url:'' },
      {movie: 'What Lies Beneath', slug: '', url:'' },
      {movie: 'Wheels on Meals', slug: '', url:'' },
      {movie: 'Willow', slug: '', url:'' },
      {movie: 'Wizard of Oz', slug: '', url:'' },
      {movie: 'Wizard of Oz 2', slug: '', url:'' },
      {movie: 'Wrist Cutters', slug: '', url:'' },
      {movie: 'Zombieland', slug: '', url:'' },
      {movie: '10 Cloverfield Lane', slug: '', url:'' },
      {movie: '13th Warrior', slug: '', url:'' },
      {movie: '1917', slug: '', url:'' },
      {movie: '***28 Days Later', slug: '', url:'' },
      {movie: '28 Weeks Later', slug: '', url:'' },
      {movie: '***300', slug: '', url:'https://www.youtube.com/watch?v=UrIbxk7idYA' },
      {movie: '***9', slug: '', url:'https://www.youtube.com/watch?v=_qApXdc1WPY' },
    ]

    const moviesToSee = [
      {movie: 'Night Crawler', slug: '', url:'https://www.youtube.com/watch?v=u1uP_8VJkDQ' },
      {movie: 'The edge', slug: '', url:'https://www.youtube.com/watch?v=iqkcX_I5MMU' },
      {movie: 'From The Dark', slug: '', url:'https://www.youtube.com/watch?v=kKsceLZu_wg' },
      {movie: 'To Watch', slug: '', url:'https://www.youtube.com/watch?v=4Zfw8__A7ps' },
      {movie: 'Bricks(detective movie)', slug: '', url:'' },
      {movie: 'It follows', slug: '', url:'https://www.youtube.com/watch?v=HkZYbOH0ujw' },
      {movie: 'What happened to Monday', slug: '', url:'https://www.youtube.com/watch?v=5F-YEbm65a8' },
      {movie: 'Taking Lives', slug: '', url:'https://www.youtube.com/watch?v=Nfoa6QKe4e0' },
      {movie: 'Horns', slug: '', url:'https://www.youtube.com/watch?v=yg9GW3Krsi8' },
      {movie: 'Snake Eyes', slug: '', url:'https://www.youtube.com/watch?v=VucLIxy23TA' },
      {movie: 'Django Unchained', slug: '', url:'' },
      {movie: 'Parasite', slug: '', url:'' },
      {movie: 'Nightmare on Elm Street', slug: '', url:'' },
      {movie: 'The Resort', slug: '', url:'' },
      {movie: 'The Vault', slug: '', url:'' },
      {movie: 'Tusk', slug: '', url:'' },
    ]


    const renderMovies = movies.map(item => {
      return (
        <tr key={item.slug}>
          <td><a href={item.url} target ='_blank'>{item.movie}</a></td>
        </tr>
      )
    })

    const renderToSee = moviesToSee.map(item => {
      return (
        <tr key={item.slug}>
          <td><a href={item.url} target ='_blank'>{item.movie}</a></td>
        </tr>
      )
    })


    return (
      <div>
        <h2>Favorite Movies</h2>
            <table>
              <tr><th>movie</th></tr>
              {renderMovies}
            </table>

        <h2>Movies to See</h2>
            <table>
              <tr><th>movie</th></tr>
              {renderToSee}
            </table>


      </div>
    );

}

export default Movies;
